apiVersion: v1
kind: Service
metadata:
  name: sally
spec:
  type: ClusterIP
  selector:
    run: demo-app-v1 # update to demo-app-v2 for blue-green deployment
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
